In [ ]:
indioma = ('pt')

if indioma =='en':
    print('Hello, Word!!')
else:
    print('Olá Mundo!')

Olá Mundo!

In [14]:
indioma = 'pt'

mensagem='Hello, word!!!'

if indioma == 'en':
    print(mensagem)

else:
    mensagem = 'Olá mundo!!!'
    print(mensagem)

Olá mundo!!!

In [16]:
print('Informe o indioma que deseja.')

indioma = input('en para Ingês e pt para Português')
mensagem = indioma
if indioma == 'en':
    print('Hello, Word!!!')
else:
    print('Olá Mundo!!!')

Informe o indioma que deseja.
Olá Mundo!!!

VARIÁVEIS NUMÉRICAS

In [17]:
a = 10
b = 20

print(a)
print(b)

#Operações Matemáticas
print(a+b) #Soma
print(a-b) #Subtração
print(a*b) #Multiplicação
print(a/b) #Divisão

10
20
30
-10
200
0.5

In [ ]:
a = 15
b = 20

In [ ]:
a = 10
b = 3

In [19]:
#Operações Matemáticas
print(a+b) #Soma
print(a-b) #Subtração
print(a*b) #Multiplicação
print(a/b) #Divisão

13
7
30
3.3333333333333335

In [20]:
print(a**b) # a elevado a b '10 elevado a 3'
print(a//b) # Divisão Inteira
print(a/b) # Divisão Normal
print(a%b) # Módulo - Para saber o resto de uma divisão.

1000
3
3.3333333333333335
1

In [21]:
print(10%2) # 10 é PAR
print(9%2)  # 9 é IMPAR

0
1

In [22]:
a = 5.1
b = 4.2
print(a)
print(b)

5.1
4.2

In [23]:
print(a+b)

9.3

Funções matemáticas.

In [24]:
# Primeiramente preciso importar uma biblioteca de cálculos matemáticos
import math

In [28]:
print(a+b)
print(round(a+b))

c = (a+b)
print(c)
print(round(c))

9.3
9
9.3
9

In [29]:
# Função – floor – essa função arredonda os valores para baixo. 
print(math.floor(c))
# Função – ceil – essa função arredonda os valores para cima. 
print(math.ceil(c))

9
10

VARIÁVEIS DE TEXTO

- Caracter (char) 
- String (varchar)

In [ ]:
nome = 'Arione'
print(nome)

Arione

In [36]:
print('Oi! Meu nome é',nome)
print('Oi! Meu nome é '+str(nome)) # Aqui eu obrigo a saída ser uma (String)
print(f'Oi o meu nome é {nome}!')

Oi! Meu nome é Arione
Oi! Meu nome é Arione
Oi o meu nome é Arione!

In [39]:
nome = 'Arione Rodrigues Langnher'
print(nome)

Arione Rodrigues Langnher

•	Arione Rodrigues Langnher
•	0123456789.......

In [ ]:
# Acessano a primeira posição do string da variável nome
print(nome[0])

# Acessano a última posição do string da variável nome
print(nome[-1])
# Acessano a última posição do string da variável nome
print(nome[24])
# Acessando um Intervalo da String
print(nome)
print(nome[0:6])

A
r
r
Arione Rodrigues Langnher
Arione

Vamos ver mais funções para manipulação de Strings

Letras minúsculas e maiúsculas.

In [44]:
print(nome)
print(nome.lower()) #Tudo fica minúsculo
print(nome.upper()) #Tudo fica maiúsculo
print(nome.title()) #Para as iniciais ficarem maiúscula, muito útil para títulos de textos

Arione Rodrigues Langnher
arione rodrigues langnher
ARIONE RODRIGUES LANGNHER
Arione Rodrigues Langnher

In [ ]:
email = 'arionebh@gmail.com'
print(email)

arionebh@gmail.com

In [47]:
email = '  arionebh@gmail.com '
print(f"e-mail'{email}'")

e-mail'  arionebh@gmail.com '

Podemos utilizar algumas funções para corrigir essa situação, para remover os espaços em volta.

In [50]:
# Removendo do começo, remova os espaços da esquerda, função: lstrip()
print(f"email'{email.lstrip()}'")
# Removendo do final, remova os espaços da direita, função: lstrip()
print(f"email'{email.rstrip()}'")
# Removendo da esquerda e direita, remova os espaço entre os textos, função: strip()
print(f"email'{email.strip()}'")

email'arionebh@gmail.com '
email'  arionebh@gmail.com'
email'arionebh@gmail.com'

In [51]:
print(nome)

Arione Rodrigues Langnher

In [62]:
# Quero que ele me diga qual posição está o caractere ‘r’
print(nome.find('e'))
print(nome.find('L'))

#quantas vezes um determinado caractere aparece.
print(nome.count('e'))
# Para saber quantos caracteres possui a nossa string/texto
print(len(nome))

print(len(email)) # Para saber quantos caracteres possui a nossa string/texto (Aqui ele conta com os espaços)
# Para saber quantos caracteres possui a nossa string/texto do meu email (Aqui ele remove os espaços)
print(len(email.strip())) 
# É só acrescentar a frente da variavel 'email' a função .strip() nao muda muita coisa no código não.

# Verificando se o e-mail possui um @, aqui ele fala em qual posição está.
print(email.find('@')) 
# Posso verificar se um determinado texto/string começa com um determinado caractere:
print(nome.startswith('Arione'))
# Posso verificar se um determinado texto/string termina com um determinado caractere:
print(nome.endswith('Arione'))
# Posso validar se o email termina com ‘.com’
print(email.endswith('.com')) 

# Aqui eu coloco a variável email retirando os espaços e já coloco a mesma ajustada dentro da variável email_fixed
email_fixed = email.strip()
print(email_fixed)

# Posso utilizar a função .replece() para substituir um outro domínio de e-mail por exemplo. Substituo o ‘gmail’ para ‘hotmail’
print(email.replace('gmail','hotmail'))

5
17
3
25
21
18
10
True
False
False
arionebh@gmail.com
  arionebh@hotmail.com

TRABALHANDO COM LISTAS E BOOLEANOS

In [ ]:
nome = 'Arione Rodrigues Langnher'
print(nome)

# Transformar esse texto em uma lista.
# Separando os nomes em lista
nome_lista = nome.split(' ') 
print(nome_lista)

Arione Rodrigues Langnher
['Arione', 'Rodrigues', 'Langnher']

In [78]:
# Posso adicionar um outro item também usando a função .append(‘texto’)
# Adicionando um item na lista
nome_lista.append('38') 
print(nome_lista)

# Adicionar outros registros e definir o local exato que eu quero adicionar esses itens. 
nome_lista.insert(1,'Ozeli') # Inserindo um item na posição 1
print(nome_lista)

# Removendo Item da Lista
nome_lista.remove('38')

# Removendo o item da posição 1 .pop(1)
nome_lista.pop(1) 
print(nome_lista)

# Ordenando as palavras .sort()
nome_lista.sort() 
print(nome_lista)

# Ordenando as palavras em ordem inversa .sort(reverse=True)
nome_lista.sort(reverse=True) 
print(nome_lista)

# Juntando os itens para uma única strig, ' '.join(nome_lista)
print(' '.join(nome_lista)) 

lista1 = ['Arione','Rodrigues','Langnher']
lista2 = ['Ozeli','Rodrigues']



# Fazendo a junção das duas listas
print(lista1+lista2)

['Rodrigues', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Langnher', 'Arione', '38', '38', '38', '38', '38']
['Rodrigues', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Langnher', 'Arione', '38', '38', '38', '38', '38']
['Rodrigues', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Langnher', 'Arione', '38', '38', '38', '38']
['38', '38', '38', '38', 'Arione', 'Langnher', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Rodrigues']
['Rodrigues', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Ozeli', 'Langnher', 'Arione', '38', '38', '38', '38']
Rodrigues Ozeli Ozeli Ozeli Ozeli Ozeli Ozeli Ozeli Ozeli Ozeli Ozeli Langnher Arione 38 38 38 38
['Arione', 'Rodrigues', 'Langnher', 'Ozeli', 'Rodrigues']

Variáveis Booleanas

Existem variáveis que são do tipo booleanas. 

Variáveis booleanas é se é True ou False (Verdadeiro, Falso)

Elas simplesmente vão definir se é verdadeiro ou falso

In [1]:
vbool = True
print(vbool)

vbool = False
print(vbool)

True
False

In [ ]:

vbool = 'Arione' in lista1 # Verificar se um determinado item/valor/elemento está contida na lista.
print(vbool)

vbool = 'Arione' in lista2 # Verificar se um determinado item/valor/elemento está contida na lista.
print(vbool)

CONDICIONAIS E LAÇOS DE REPETIÇÃO

O que são blocos de código.**

***BLOCOS DE CÓDIGO*** -
Em python se eu quiser criar uma coisa com mais de uma linha, eu vou ter que ***identar.***
Toda vez que eu preciso organizar as linhas em bloco de código, eu vou colocar o **: dois pontos**
vou dar um **[enter]**, automaticamente perceba que o cursor vai um **pouco para a direia.**
Eu posso também ajustar dando um [tab] do meu teclado.
O print imprime qualquer coisa!
--> Porém esse print aqui é **exclusivamente/pertence** do **if 0==0:**, pois depois do **: pontos**
ele tem que **respeitar uma hierarquia/bloco de código.**

A **identação em Python** é o **espaço em branco no início de uma linha de código**, e serve para definir blocos de código. É uma parte obrigatória da linguagem — diferente de outras linguagens como C, Java ou JavaScript, onde você usa {} para delimitar blocos, no Python isso é feito com a **indentação.**

Para que serve?

**A indentação define quais comandos pertencem ao mesmo bloco.**

Por exemplo, quando você cria uma **função, um if, for, while, etc., o que estiver identado será considerado parte daquele bloco.**

Exemplo:

if 10 > 5:

    print("10 é maior que 5")

    print("Esse bloco faz parte do IF")

print("Esse não faz parte do IF")

Nesse exemplo:

As duas primeiras print() estão dentro do bloco if, porque estão indentadas (espaçadas).

A última print() está fora do if, porque não está indentada.

Como fazer a indentação?

Normalmente se usa 4 espaços ou 1 tabulação (mas nunca misture os dois).

O PEP 8 (guia de estilo do Python) recomenda 4 espaços por nível de indentação.

O que acontece se não usar?

O Python vai gerar erro. Exemplo:

if 10 > 5:
print("Erro!")  # ERRO de indentação
Resultado:

IndentationError: expected an indented block

**Resumo:**

**Indentação** = espaços que indicam o nível do bloco de código.

É obrigatória no Python.

Serve para organizar e estruturar o código.

Ajuda a manter o código legível e bem organizado.


O que são condicionais.**

***CONDICIONAIS***

Condicionais são **FORMAS** que nós temos de **MODIFICAR** o **FLUXO** do **código!**

Se **essa condição for cumprida**, **faça isso**, se ela **não for cumprida faça aquilo.**

As **condicionais** me dizem se algo é **VERDADEIRO** ou **FALSO**.

***Condicionais é o que vai dar inteligência ao código!***


***Como saber se um número é par ou impar?***
Par ou ímpar: como diferenciar?
Os números pares são aqueles divisíveis por 2.
Ou seja, se dividirmos um número por 2 e o resto da divisão for zero, trata-se de um número par.
Um número é considerado ímpar se ele não for divisível por 2, isto é, se dividirmos esse número por 2 e ele deixar um resto igual a 1.

if num % 2 == 0:

Nessa instrução, num é o número que se quer verificar.
Um número é par quando é divisível por 2, ou seja, quando o resto da divisão por 2 é zero.
Já um número é ímpar quando não é divisível por 2, ou seja, quando o resto da divisão por 2 é 1.

In [ ]:
nota = 85
print(nota)

85

In [4]:
nome = 85

if nota >= 70:
    print('Aprovado')

else:
    print('Reprovado')

Aprovado

In [5]:
nota = 65

if nota >= 70:
    print('Aprovado')

else:
    print('Reprovado')

Reprovado

In [ ]:
# Vamos colocar a validação nota >= 70 dentro de uma nova variável is_aprovado sendo que a variável nota = 65
nota = 65

is_aprovado = nota >= 70
print(is_aprovado)

False

In [7]:
# Esse IF aqui ele avalia somente se for falso ou verdadeiro, ou seja, aprovado ou reprovado. 
# Validando o início da variável principal, que no caso aqui é a nota = 65

if is_aprovado:
    print('Aprovado')

else:
    print('Reprovado')

Reprovado

In [8]:
nota = 85

is_aprovado = nota >= 70
print(is_aprovado)

True

In [9]:
if is_aprovado:
    print('Aprovado')

else:
    print('Reprovado')

Aprovado

Fazendo condição IF, ELIF e ELSE

In [10]:
nota = 85

if nota >=90:
    print('Aprovado com louvor A')
elif nota >=70:
    print('Nota B')
else:
    print('Reprovado')

Nota B

In [11]:
nota = 95

if nota >=90:
    print('Aprovado com louvor A')
elif nota >=70:
    print('Nota B')
else:
    print('Reprovado')

Aprovado com louvor A

**O que são LOOPS ou Laços de Repetição?**

Você quer fazer uma coisa **mais de uma vez**.

Você deseja fazer uma **coisa várias vezes.**

→ ***Loop é eu repetir uma coisa UMA, DUAS, VÁRIAS VEZES o quanto for necessário.***

***Loop, ou laço, é uma estrutura de controle em programação que executa repetidamente um bloco de código.***
 A repetição ocorre até que uma condição especificada seja alcançada.
Os loops são estruturas fundamentais em programação e podem ser utilizados para automatizar tarefas.

→ Eles são úteis quando você quer executar uma **mesma tarefa várias vezes sem precisar copiar o mesmo código várias vezes.**

Existem três tipos principais de loops nas linguagens de programação mais comuns:

**for** – usado quando você **sabe exatamente** quantas vezes quer repetir algo.

Exemplo em Python:

for i in range(5):

    print("Olá", i)

**while** – usado quando você **não sabe** quantas vezes vai repetir, mas sabe a condição que precisa ser verdadeira para continuar.
Exemplo:

x = 0

while x < 5:

    print("Contando", x)

    x += 1

**do while** (não existe em Python, mas em outras linguagens como C, Java, etc.) – parecido com o while, mas garante que o bloco será executado pelo menos uma vez, mesmo que a condição seja falsa logo depois.

***Onde os loops são úteis?***

1. Para percorrer listas ou arquivos;

2. Para repetir cálculos;

3. Para criar menus interativos;

4. Para simular comportamentos repetitivos.

**Como utilizar While.**

Toda vez em um código qualquer que eu precisar repetir alguma coisa, seja um cálculo, seja uma palavra, uma expressão, uma função,
uma consulta ao banco de dados, toda vez que eu precisar ***repetir algo mais de uma vez***, eu tenho **DUAS FORMAS DE FAZER.**

1. Eu posso criar DUAS LINHAS de CÓDIGO ou QUANTAS LINHAS DE CÓDIGOS FOR NECESSÁRIO.
2. Ou eu posso criar simplesmente um LOOP.

Vamos fazer um laço de repetição, utilizando o While

Antes de mais nada eu crio um Contador com o valor de 1

Depois eu crio um laço de repetição while (Enquanto) o Contador que é a variável Contador for <=10, exibe o valor do contador e vai adicionando mais 1 durante cada interação até chegar no valor 10 

Aqui o contador começou com o valor 1

Enquanto o while contador for <=10 vai printando o valor

Lembrando que a estrutura do python é seguida por identação, ou seja, aqui o que está ‘dentro’ do while ele valida, identação é o espaço a frente na linha.

Cuidado! Você tem que colocar o incremento do contador, que é o contator +=1, por que só assim ele vai incrementando valor por valor.

In [17]:
contador = 1

while contador <=10:
    print(contador)
    contador += 1

1
2
3
4
5
6
7
8
9
10

Vamos utilizar um outro Laço de Repetição que é o FOR

Aqui ele fez, para/FOR cada ‘i’ em/in na lista [1,2] adiciona cada item ao  ‘i’.

E para/FOR e cada vez estou pedindo para imprimir.

Aqui ele tem dois itens que é a lista [1,2] Le vai passar um item por vez e vai executar as ações do bloco de código aqui dentro, no caso imprimir.

In [ ]:
for i in [1,2]:
    print(i)

1
2
1
2
3
4
5
6
7
8
9
10

Quando queremos fazer um teste ou utilizar um intervalo fictício, também podemos utilizar a função de range(1, 10)
Aqui com a função range(1, 10) ele vai criar de 1 a 10 registros e vamos imprimir isso em tela do 1 ao 9 ele imprime até antes do 10, se fosse do 1, 11 ele iria imprimir até 10:

In [ ]:
for i in range(1, 11):
    print(i)

In [21]:
for i in range(1, 11):
    print(f'valor: {i}')

valor: 1
valor: 2
valor: 3
valor: 4
valor: 5
valor: 6
valor: 7
valor: 8
valor: 9
valor: 10

Outra coisa que podemos fazer é, dentro do laço de repetições, colocar algumas condições:

Se ‘i’ for igual a ‘5’ eu vou usar o break

Aqui ele vai do 1, 2, 3, 4 e 5, mas quando chegar no 5 ele vai parar.

Ele validou aqui dentro do bloco de código o i é igual a 5, sim! Então para! Podia ser outra coisa também! Depende o que você programou dentro do bloco de código.

In [22]:
for i in range(1, 11):
    print(f'valor: {i}')
    if i == 5:
        break

valor: 1
valor: 2
valor: 3
valor: 4
valor: 5

**Diferença da utilização do WHILE e o FOR**

Perceba o seguinte que, aqui eu não estou utilizando o incremento do i ou seja, i +=1, pois não precisa desse contador, por que o FOR ele trabalha de forma diferente, ele vai pegar cada registro que a gene tem aqui ‘para FOR’ cada ‘i ou item’ ou ‘registro’ vai ter uma lista de 5 registros por exemplo, vai pegar 1, 2, 3, 4, 5, vai pegar um por vez e aplicar na lógica abaixo. 

Já o WHILE ele vai repetir todas essas instruções ‘while contador <=10:’ até que essa condição se torne verdadeira com o auxílio do contador para efetuar o incremento contador +=1

In [25]:
for i in range(1, 11):
    print(f'valor: {i}')
    if i == 5:
        continue

valor: 1
valor: 2
valor: 3
valor: 4
valor: 5
valor: 6
valor: 7
valor: 8
valor: 9
valor: 10

In [26]:
# 1 é igual a 5, NÃO. Então ele foi imprimindo todos os valores que são diferentes de 5, ou seja, se for igual a 5 continue, ele pula a impressão do valor 5. 

for i in range(1, 10):
    if i == 5:
        continue
    else:
        print(f'valor: {i}')

valor: 1
valor: 2
valor: 3
valor: 4
valor: 6
valor: 7
valor: 8
valor: 9

In [27]:
for i in range(1, 10):
    if i % 2 == 0:
        print(f'Par: {i}')
    else:
        print(f'Impar: {i}')

Impar: 1
Par: 2
Impar: 3
Par: 4
Impar: 5
Par: 6
Impar: 7
Par: 8
Impar: 9

**DICIONÁRIO E REVISÃO**

Perceba que tudo o que utilizamos até agora teve limite?
No caso agora aprendendo dicionários, isso será bem diferente!
Como vimos o exemplo de listas de notas fiscais, vimos que tem como apenas colocar os números das notas fiscais
dentro da lista e nada mais! Mas sabemos que a nota fiscal além de número, possui outras informações referente a esses números:
data de emissão, pedido, cliente, produtos e etc.

	Dicionários são criados através de chaves { : } e dois pontos.

	O conceito de Dicionários é: (chave) e (valor).

	Mas porque o nome dicionário? 

	É como se fosse dicionário mesmo, você procura o nome em um dicionário procurando por uma determinada letra, por exemplo, a palavra python, você busca pela palavra 'p' e vai ter lá na página do dicionário,
o nome python: é uma linguagem de programação..., ou seja, o valor da palavra python, o significado da palavra python vai estar alí do lado direito da palavra.
E aqui em dicionário na programação, usamos a {chave ** : ** valor/significado}
Ex: {'python':'Linguagem de programação','Criada_em':'1989'}
       chave            valor                                  chave        valor

	Obs: Quando você trabalhar com dicionários, você vai ter que quebrar linhas, pois senão você vai ficar muito confuso.

Criando Objetos! Chamamos dicionários de Objetos também!

	Criaremos objetos, o objeto nf que contém o número da nota fiscal eletrônica, e a data de emissão. Isso é um objeto!

	Criaremos objetos utilizando DICIONÁRIOS e LISTAS.






PARA MEMORIZAR o que são:

ARRAYS/LISTAS

DICIONÁRIOS/OBJETOS

 LISTAS COM DICIONÁRIOS.

arrays/lista = [ ]

dicionários = {' ':' ',' ':' '}

lista_com_dicionários = [
{
'nome':'Arione',
},
{
'Idade':'37'
},
'Profissão':'Cientista de Dados'
}
                        ]

In [28]:
pessoa = {'nome':'Arione Rodrigues Langnher', 
          'idade': '38',
         'assinante':True}

In [29]:
# Aqui eu acesso o ‘objeto’ pessoa e o ‘atributo’ nome
print(f'Usuario: {pessoa['nome']}')

Usuario: Arione Rodrigues Langnher

In [39]:
'''
Tem uma outra forma que eu posso exibir esse conteúdo, utilizando múltiplas linhas. 
Informe 3 aspas duplas “”” ou 3 aspas simples ‘’’ no começo e lá no final 
Assim eu consigo exibir outro item na linha de baixo, ou seja, eu posso quebrar linha, e exibir outro conteúdo, ou seja, uma string multilinha.
'''

print(f"""Usuario: {pessoa['nome']}
          Idade: {pessoa['idade']}""")

print(f'''Usuario: {pessoa['nome']}
         Idade: {pessoa['idade']}
         Assinante:{pessoa['assinante']}''')

Usuario: Arione Rodrigues Langnher
          Idade: 38
Usuario: Arione Rodrigues Langnher
         Idade: 38
         Assinante:True

Quando desejo ter mais de um objeto, eu consigo colocar isso em uma lista.
Vamos criar um objeto vazio pessoas = []
Vamos adicionar objetos .append dentro dessa lista de pessoas = []

In [48]:
pessoas = []

pessoas.append({'Nome':'Arione Rodrigues Langnher', 
           'Idade': '38',
           'Assinante':True})

pessoas.append({'Nome':'Carla Silva', 
               'Idade': '47',
               'Assinante':False})

In [43]:
#Ao invés de utilizar esse tipo de exibição ou impressão ‘print’ para cada registro ou saída, podemos utilizar um for para essas exibições ou impressões:

for pessoa in pessoas:
    print(f'Nome:{pessoa['Nome']}')
    print(f'Idade:{pessoa['Idade']}')
    print(f'Assiante:{pessoa['Assinante']}')
    print('...')

Nome:Arione Rodrigues Langnher
Idade:38
Assiante:True
...
Nome:Carla Silva
Idade:47
Assiante:False
...

In [47]:
for pessoa in pessoas:
    print(f'Nome:{pessoa['Nome']}')
    print(f'Idade:{pessoa['Idade']}')
if pessoa['Assinante']:
        print(f'Assinante: Sim')
else:
    print(f'Assinante: Não')
    print('...')

Nome:Arione Rodrigues Langnher
Idade:38
Nome:Carla Silva
Idade:47
Assinante: Não
...

**PANDAS - INTRODUÇÃO E SERIES**

Vamos agora conhecer uma biblioteca importantíssima para análise de dados.

PANDAS

Tudo o que estudamos até agora sobre python: variáveis, strings, dados numéricos, listas, tuplas, dicionários, condicionais lógicos e estruturas/laços de repetição, vamos agora trabalhar com tudo isso com as bibliotecas.

In [51]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

Instale o pandas no ambiente correto

Abra o terminal dentro do VSCode (Ctrl + ') e execute:

pip install pandas

In [52]:
pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.2-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\arion\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\arion\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.9 MB 11.7 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.9 MB 14.2 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 14.8 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 13.5 MB/s  0:00:00
Downloading numpy-2.4.2-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ------------ --------------------------- 3.9/12.4 MB 21.4 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.4 MB 18.8 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 17.7 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 15.4 MB/s  0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.2 pandas-3.0.1 tzdata-2025.3

In [1]:
import pandas as pd

In [3]:
serie = pd.Series([10,20,30])

In [ ]:
print(serie)

0    10
1    20
2    30
dtype: int64

In [7]:
serie = pd.Series([10,20,30], index=['a','b','c'])
print(serie)

a    10
b    20
c    30
dtype: int64

In [10]:
serie = pd.Series([10,20,30], index=['a','b','c'], name='Idades')
print(serie)

a    10
b    20
c    30
Name: Idades, dtype: int64

In [11]:
idades = pd.Series([25,30,35,40,45], name='Idades')
print(idades)

0    25
1    30
2    35
3    40
4    45
Name: Idades, dtype: int64

Funções dentro das Séries Pandas

In [12]:
idades.count()

np.int64(5)

In [14]:
#Vamos estruturar isso de uma forma melhor como já vimos.

print(f'O total de registros é :{idades.count()}')

O total de registros é :5

In [17]:
# Se eu colocar mais um valor, mais uma idade.

idades = pd.Series([25,30,35,40,45,36], name='Idades')
print(idades)

print(f'O total de registros é :{idades.count()}')

0    25
1    30
2    35
3    40
4    45
5    36
Name: Idades, dtype: int64
O total de registros é :6

In [31]:
# FUNÇÔES

# Contagem de Elementos
print(f'O total de registros é :{idades.count()}')
# Média dos valores
print(f'A média das idades é :{idades.mean()}')
# Soma dos Valores
print(f'A soma das idades é : {idades.sum()}')
# Valor máximo
print(f'A idade máxima é: {idades.max()}')
# Valor Mínimo
print(f'A idade mínima é: {idades.min()}')
# Valor Mediano
print(f'A mediana das idades é: {idades.mean()}')
# Uma prévia resumida valores estatísticos
print(idades.describe())

O total de registros é :7
A média das idades é :40.285714285714285
A soma das idades é : 282
A idade máxima é: 71
A idade mínima é: 25
A mediana das idades é: 40.285714285714285
count     7.000000
mean     40.285714
std      15.007934
min      25.000000
25%      32.500000
50%      36.000000
75%      42.500000
max      71.000000
Name: Idades, dtype: float64

In [ ]:

idades = pd.Series([25,30,35,40,45,36,71], name='Idades')

PANDAS - DATAFRAMES

DataFrames é uma estrutura de tabulação de dados que temos no pandas.

In [1]:
# Importando a biblioteca pandas

import pandas as pd

Existem varias formas para estruturar um dataframe

Vamos criar um utilizando um dicionário.

Uma estrutura de dados que já vimos

Aqui temos um dicionário e os valores são as listas.

Eu tenho 3 listas, cada lista para um atributo com 4 registros cada um.

Aqui vamos definir o atributo columns com a lista de cada uma das colunas, agora fica fácil eu tenho 1 registro em cada lista e eu tenho o nome da coluna que vai ser associada a cada uma das respectivas colunas do nosso dataframe

•	Tudo vai depender de como você tem esses dados e como você via querer estruturá-los

In [ ]:
dados = {
    'nome' : ['João','Maria','José','Pedro'],
    'idade': [12, 13, 14, 15],
    'salario': [1000, 2000, 1500, 3000] 
    
}
df = pd.DataFrame(dados)
print(df)

Para eu transformar esse dicionário aqui em um dataframe vou fazer no seguinte formato:

Aqui temos os dados tabulados, através de colunas e linhas isso é um dataframe. 

Temos os valores das linhas que são os índices de cada linha e de cada coluna específica.

In [3]:
df = pd.DataFrame(dados)
print(df)

    nome  idade  salario
0   João     12     1000
1  Maria     13     2000
2   José     14     1500
3  Pedro     15     3000

In [5]:
dados = [
    ['João', 12, 1000],
    ['Maria',13, 2000],
    ['José', 14, 1500],
    ['Maria',15, 3000]
    ]


df = pd.DataFrame(dados, columns = ['nome', 'idade', 'salário'])
print(df)

    nome  idade  salário
0   João     12     1000
1  Maria     13     2000
2   José     14     1500
3  Maria     15     3000

In [6]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     4 non-null      str
 1   idade    4 non-null      int64
 2   salário  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes
None

In [ ]:
# Para descrever o DataFrame especificamente uma coluna
print(df['nome'].describe())

count         4
unique        3
top       Maria
freq          2
Name: nome, dtype: object

In [ ]:
# Para descrever o DataFrame especificamente uma coluna
print(df['idade'].describe())

count     4.000000
mean     13.500000
std       1.290994
min      12.000000
25%      12.750000
50%      13.500000
75%      14.250000
max      15.000000
Name: idade, dtype: float64

In [ ]:
# Para descrever o DataFrame, descreve as colunas numéricas
print(df.describe())

           idade      salário
count   4.000000     4.000000
mean   13.500000  1875.000000
std     1.290994   853.912564
min    12.000000  1000.000000
25%    12.750000  1375.000000
50%    13.500000  1750.000000
75%    14.250000  2250.000000
max    15.000000  3000.000000

In [ ]:
# Algumas funções
print(df.shape)
print(df.columns)
print(df.index)

(4, 3)
Index(['nome', 'idade', 'salário'], dtype='str')
RangeIndex(start=0, stop=4, step=1)

In [ ]:
# Detalhar o cabeçalho do DataFrame
print(df.head())
print(df.head(2))

    nome  idade  salário
0   João     12     1000
1  Maria     13     2000
2   José     14     1500
3  Maria     15     3000
    nome  idade  salário
0   João     12     1000
1  Maria     13     2000

In [ ]:
# Se eu quero ver os últimos registros que foram adicionados. 
# Aqui ele pega os últimos dois registros do dataframe.

print(df.tail(2))

    nome  idade  salário
2   José     14     1500
3  Maria     15     3000

MANIPULANDO DATAFRAMES


Vamos aprender como manipular e trabalhar nesse dataframe, por muitas vezes recebemos um dataframe extenso com muitas informações, e necessariamente não temos que trabalhar em todos os dados completamente. Precisamos organizar e separar os dados necessário para a análise.

In [ ]:
import pandas as pd

dados = {
    'nome' : ['João','Maria','José','Pedro'],
    'idade': [12, 13, 14, 15],
    'salario': [1000, 2000, 1500, 3000] 
    
}
df = pd.DataFrame(dados)
print(df)

    nome  idade  salario
0   João     12     1000
1  Maria     13     2000
2   José     14     1500
3  Pedro     15     3000

In [ ]:
# Exibindo apenas uma coluna do DataFrame
print(df['nome'])

0     João
1    Maria
2     José
3    Pedro
Name: nome, dtype: str

In [3]:
# Exibindo o DataFrame Inteiro
print(df)

    nome  idade  salario
0   João     12     1000
1  Maria     13     2000
2   José     14     1500
3  Pedro     15     3000

In [4]:
# Posso exibi-la por meio de variável

colunas = 'nome'
print(df[colunas])

0     João
1    Maria
2     José
3    Pedro
Name: nome, dtype: str

In [5]:
# Posso exibir como string ou posso exibir também como uma lista

colunas = ['nome']
print(df[colunas])

    nome
0   João
1  Maria
2   José
3  Pedro

In [ ]:
# Adicionando mais uma coluna na visualização de lista
colunas = ['nome','idade']
print(df[colunas])

    nome  idade
0   João     12
1  Maria     13
2   José     14
3  Pedro     15

In [ ]:
# Não tem necessidade de declarar isso dentro de uma variável como no exemplo anterior, mas foi apenas uma das maneiras de exibir. 
# Podemos declarar diretamente as colunas dentro do print
# (tem que ter dois [[]] colchetes seguidos.) 1 para fazer o filtro do dataFrame e 1 para declarar as colunas a sua listagem.

print(df[['nome','idade']])

    nome  idade
0   João     12
1  Maria     13
2   José     14
3  Pedro     15

In [7]:
# Criando outro DataFrame a partir do original, filtrar e criar um outro dataFrame para facilitar a minha leitura.

# Crio a nova variável do novo DataFrame apontando para esse resultado do DataFrame anterior.

df2 = df[['nome','idade']]
print(df2)

    nome  idade
0   João     12
1  Maria     13
2   José     14
3  Pedro     15

In [8]:
# Agora tenho dois Dataframes

print(df)
print(df2)

    nome  idade  salario
0   João     12     1000
1  Maria     13     2000
2   José     14     1500
3  Pedro     15     3000
    nome  idade
0   João     12
1  Maria     13
2   José     14
3  Pedro     15

In [9]:
# Visualizando apenas as linhas de índice 0 e 2

print(df[0:2])

    nome  idade  salario
0   João     12     1000
1  Maria     13     2000

In [ ]:
# Criando um outro dataframe df3  o terceiro a partir do dataframe 2 d2 com duas linhas
df3 = df2[0:2]
print(df3)

    nome  idade
0   João     12
1  Maria     13

In [ ]:
# Fazendo uma busca dos registros pelo índice

nome     João
idade      12
Name: 0, dtype: object

In [14]:
# Quero buscar o índice 2 do daframe 1 o orignial

print(df.iloc[2])

nome       José
idade        14
salario    1500
Name: 2, dtype: object

In [18]:
# Podemos também fazer algumas validações, podemos ordenar esse dataframe 
# Vamos ordenar pelo nome

print(df.sort_values(by='nome'))


print(df.sort_values(by='salario'))

    nome  idade  salario
2   José     14     1500
0   João     12     1000
1  Maria     13     2000
3  Pedro     15     3000
    nome  idade  salario
0   João     12     1000
2   José     14     1500
1  Maria     13     2000
3  Pedro     15     3000

In [ ]:
# Vamos ordenar pelo salário do maior para o menor.
#Aqui a ascendência será False, pois queremos visualizar como dessedente. 

print(df.sort_values(by='salario', ascending=False))

    nome  idade  salario
3  Pedro     15     3000
1  Maria     13     2000
2   José     14     1500
0   João     12     1000

In [ ]:
# Criando um data frame 2 e fazendo uma filtragem onde vou pegar do dataframe 1 a coluna idade e validar se ela é <= 14.
# Ele vai sobre sobescrever o outro df2 criado anteriormente

df2 = df[df['idade'] <=14]
print(df2)

    nome  idade  salario
0   João     12     1000
1  Maria     13     2000
2   José     14     1500

In [ ]:
# Copiando e visualizando com outras regras idade e salário
# Idade <= 14 e salario >= 1500
df2 = df[(df['idade'] <=14) & (df['salario'] >= 1500)]
print(df2)

    nome  idade  salario
1  Maria     13     2000
2   José     14     1500

Fazendo alguns cálculos para adicionar outras colunas

In [31]:
print(df)

    nome  idade  salario
0   João     12     1000
1  Maria     13     2000
2   José     14     1500
3  Pedro     15     3000

In [3]:
# Adicionando uma nova coluna de ano de nascimento, ‘ano_nascimento’ igual  2025 – a coluna idade dentro do dataFrame original
df['ano_nascimento'] = 2025 - df['idade']

In [5]:
print(df)

    nome  idade  salario  ano_nascimento
0   João     12     1000            2013
1  Maria     13     2000            2012
2   José     14     1500            2011
3  Pedro     15     3000            2010

In [ ]:
# Deletando alguma coluna do dataframe
# df vai = ao df e drop e as colunas que queremos deletar e o eixo=1 ou seja estou deletando uma coluna. 

df = df.drop(columns=['ano_nascimento'], axis=1)
print(df)

ValueError: Cannot specify both 'axis' and 'index'/'columns'

In [6]:
# Deletando alguma coluna do dataframe
# df vai = ao df e drop e as colunas que queremos deletar e o eixo=1 ou seja estou deletando uma coluna. 
df = df.drop(columns=['ano_nascimento'])
print(df)

    nome  idade  salario
0   João     12     1000
1  Maria     13     2000
2   José     14     1500
3  Pedro     15     3000

In [ ]:
# Deletando uma linha do dataframe
# Deletando o primeiro registro aqui

df = df.drop(0, axis=0)
print(df)

In [10]:
print(df)

    nome  idade  salario
1  Maria     13     2000
2   José     14     1500
3  Pedro     15     3000

 ANALISANDO OS DADOS DOS DATAFRAMES

In [15]:
import pandas as pd

dados = {
    'categoria' : ['Notebook','Celular','Tablet','Notebook','Celular'],
    'quantidade' : [10, 20, 15, 5, 30],
    'preco' : [3000, 2000, 1500, 3000, 3000]
}

df = pd.DataFrame(dados)

In [18]:
print(df)

  categoria  quantidade  preco
0  Notebook          10   3000
1   Celular          20   2000
2    Tablet          15   1500
3  Notebook           5   3000
4   Celular          30   3000

In [23]:
# Quero saber o valor total sobre esses ativos

# Vou pegar o dataframe df, e calcular o valor total, para calcular o valor total eu vou dizer que é a quantidade * o preço individual, aí eu vou ter o valor total. 

df['valor_total'] = df['quantidade'] * df['preco']
print(df)

  categoria  quantidade  preco  valor_total
0  Notebook          10   3000        30000
1   Celular          20   2000        40000
2    Tablet          15   1500        22500
3  Notebook           5   3000        15000
4   Celular          30   3000        90000

In [24]:
# Agrupando por categoria e somando o valor total de cada um.
# Aqui temos por categoria, ou seja, eu agrupei essas categorias que são iguais e somei o valor total.
# Agrupei as categorias que são iguais e somei o total.

valor_por_produto = df.groupby('categoria')['valor_total'].sum()
print(valor_por_produto)

categoria
Celular     130000
Notebook     45000
Tablet       22500
Name: valor_total, dtype: int64

In [22]:
# Agrupando por categoria e somando o valor total de cada um sem dar nome

valor_por_produto = df.groupby('categoria').sum()
print(valor_por_produto)

           quantidade  preco
categoria
Celular            50   5000
Notebook           15   6000
Tablet             15   1500

In [35]:
# Ordenando o produto pelo valor, ordenação por valores crescente
valor_ordenados = valor_por_produto.sort_values(ascending=False)
print(valor_ordenados)

categoria
Celular     130000
Notebook     45000
Tablet       22500
Name: valor_total, dtype: int64

In [37]:
# Fazendo outeo DataFrame copiado no DF original

df2 = df.copy()

In [38]:
print(df2)

  categoria  quantidade  preco  valor_total
0  Notebook          10   3000        30000
1   Celular          20   2000        40000
2    Tablet          15   1500        22500
3  Notebook           5   3000        15000
4   Celular          30   3000        90000

In [ ]:
# Deletando a coluna valor_total do df2

df2 = df2.drop('valor_total', axis=1)

In [43]:
print(df2)

  categoria  quantidade  preco
0  Notebook          10   3000
1   Celular          20   2000
2    Tablet          15   1500
3  Notebook           5   3000
4   Celular          30   3000

In [ ]:
# Vamos alterar os tipos de valores de preço
# Vamos alterar os tipos de valores de preço, o preço será convertido para ponto flutuante, é um dos tipos de variáveis que quero converter, estava do tipo INT e agora será float.
# Função: .astype(float)

df2['preco'] = df2['preco'].astype(float)
print(df2)

  categoria  quantidade   preco
0  Notebook          10  3000.0
1   Celular          20  2000.0
2    Tablet          15  1500.0
3  Notebook           5  3000.0
4   Celular          30  3000.0

In [66]:
# Vamos agora fazer um outro dataframe3 copiando o dataframe2.
# Quero aumentar 10% do preço dos produtos.

df3 = df2.copy()
df3['preco'] = df3['preco'] * 1.1
print(df3)

  categoria  quantidade   preco
0  Notebook          10  3300.0
1   Celular          20  2200.0
2    Tablet          15  1650.0
3  Notebook           5  3300.0
4   Celular          30  3300.0

In [65]:
# Deletando um DataFrame
del df3

In [69]:
# Soma dos valores de preços 
print(df3['preco'].sum())

13750.0

In [ ]:
# Vamos efetuar uma alteração para os celulares, vamos fazer um df4 copiando do df2

# Depois vou pegar o df4 e faço uma busca loc.df4 vou localizar a ‘categoria’ e vou falar que tem que ser igual == a ‘celular’, 
# quando encontrar a ‘categoria’ == a ‘celular’, vai fazer o seguinte pegar o ‘preco’ e com este ‘preco’ vai multiplicar o valor por *= 1.1

df4 = df2.copy()
df4.loc[df4['categoria'] == 'celular','preco'] *= 1.1
print(df4)

# Aqui todos os ítens que são da 'categoria' celular TIVERAM ESSE ACRÉSCIMO de 10%

  categoria  quantidade   preco
0  Notebook          10  3000.0
1   Celular          20  2000.0
2    Tablet          15  1500.0
3  Notebook           5  3000.0
4   Celular          30  3000.0

In [71]:
'''
Podemos fazer validações e regras mais complexas.
Vamos fazer uma validação múltipla.
Vou pegar aqui entre parênteses () essa validação & e validar também quando o ‘preco’ for >= 2500 e esse valor vamos fazer o oposto, dar um desconto de 10%

Aqui o celular que custava menos de 2500 ele vão foi alterado, como o caso do celular de 2000. 
Agora o que custava 3000 teve um desconto de 10% de 3000 o desconto foi de 300 reais, logo o valor ficou 2700.
'''
df4 = df2.copy()
df4.loc[(df4['categoria'] == 'celular') & (df4['preco'] >= 2500),'preco'] *= 0.9
print(df4)

  categoria  quantidade   preco
0  Notebook          10  3000.0
1   Celular          20  2000.0
2    Tablet          15  1500.0
3  Notebook           5  3000.0
4   Celular          30  3000.0

**MÓDULO 03 - 1.3_B - SQL - SQLITE E COMANDOS DDL**


Vamos aprender sobre dois uso do DDL (Data Definition Language) que é a linguagem de definição de um banco de dados: Create Alter Drop Truncate - Criar/alterar estrutura do banco e sobre o SQLite.


SQLite – SQLite é uma biblioteca é um recurso um projeto, a onde conseguimos ter um banco de dados em memória. É um tipo de banco de dados mais leves e justamente para esses momentos, situações onde estamos trabalhando com integração sem necessariamente ter uma instância de banco de dados.

Lembrando que em ambiente de produção e no seu trabalho vai ter uma instância de banco de dados e a gente faz essa conexão, aqui precisamos de um usuário e senha ou seja, uma credencial para conectar nesse banco de dados e aí vamos utilizar grande parte dos comandos que vamos ver aqui.

Como estamos utilizando o python nós vamos utilizar a biblioteca SQL por meio do import sqlite3

In [72]:
import sqlite3

Criando uma conexão utilizando o sqlite que vai conectar nesse banco de teste que estou criando aqui.
Preciso criar um cursor que vai criar essa conexão é uma forma de conectar com o banco de dados e executar esses comandos.
Esse cursos é para executar os comandos. 
1. Tenho uma conexão
2. Tenho esse cursor

In [73]:
con = sqlite3.connect('teste.db')
cur = con.cursor()

In [76]:
# Fazendo o comando de criação de uma tabela.
# Como eu quero utilizar multiplas linhas, vamos utilizar 3 aspas duplas """ no começo e no final """
# Usamos o CREATE TABLE para criar a tabela e posso colocar uma condição se a tabela não existe IF NOT EXISTS categorias
# Dentro da tabela categorias, ou seja, dentro dessa planilha e dado tabulado eu vou criar as colunas ()
# Aqui eu informo quais colunas que irão ser:
# Id do tipo INTEGER é uma PRIMARY KEY e vai ter um autoincremento AUTOINCREMENT siginifica que cada novo registro ele vai adicionar 1 nessa chave a sucessivamente
# coluna NOME do tipo TEXT e nao pode ser nulo NOT NULL

cur.execute ("""
CREATE TABLE IF NOT EXISTS categorias (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL)
""")

In [83]:
# Quero obter essas informações da tabela que cabamos de criar.

# utilizamos o comando: cur.execute("""PRAGMA table_info(categorias)""")
# Depois colocamos essas informações dentro de uma variável 'estrutura' e o cur.fetchall() recupera todas as informações que ele executou
# Vou colocar dentro de um 'for' cada coluna in estrutura (tudo que estiver em estrutura, cada item associa a coluna e printa a coluna)
# print(coluna)

cur.execute("""PRAGMA table_info(categorias)""")
estrutura = cur.fetchall()
for coluna in estrutura:
    print(coluna)

# Aqui eu consigo ver que essa tabela categorias tem 2 colunas. ID que é inteiro e nome que é texto.

(0, 'id', 'INTEGER', 0, None, 1)
(1, 'nome', 'TEXT', 1, None, 0)
(2, 'ativo', 'BOOLEAN', 0, None, 0)

In [ ]:
# Comando para visualizar as tabelas que temos definidas.

# Chamar o cursor de novo cur.execute("""select name from sqlite_master que é uma tabela de controle do próprio Sqlite""")
# Agora vamos filtrar onde o tipo vai ser tabela. Aqui ele utiliza essa tabela para fazer o controle dos recursos das entidades que foram criadas que o Sqlite gerencia,
# Vou filtrar eu quero os recursos de tabelas e só os nomes.
# print para recuperar todas essas informações 

cur.execute("""select name from sqlite_master where type='table'""")
print(cur.fetchall())

# Aqui temos duas tabelas, 'categorias' e 'sqlite_sequence'

[('categorias',), ('sqlite_sequence',)]

In [ ]:
# Estruturando esse print/retorno 
# Assim ele busca como o 'objeto' - print(table)
# Assim ele busca o nome das tabelas criadas - print(table[0])

cur.execute("""select name from sqlite_master where type='table'""")
for table in cur.fetchall():
    print(table[0])

categorias
sqlite_sequence

In [ ]:
# Vamos executar mais comandos DDL para alterar o nosso banco agora
# Vamos adicionar uma nova coluna
# Chama o cursor novamente cur.execute ("""""")
# E vou executar um comando de alteração da tabela 'categorias' adicionando uma coluna chamada 'ativo' que vai ser um boleano (True ou False).

cur.execute("""ALTER TABLE categorias ADD COLUMN ativo BOOLEAN""")

In [84]:
# Revisitar no comando para ver como está agora a estrutura da tabela 

cur.execute("""PRAGMA table_info(categorias)""")
estrutura = cur.fetchall()
for coluna in estrutura:
    print(coluna)

(0, 'id', 'INTEGER', 0, None, 1)
(1, 'nome', 'TEXT', 1, None, 0)
(2, 'ativo', 'BOOLEAN', 0, None, 0)

In [ ]:
# Deletar a tabela agora

# Chama o cursor cur.execute ("""DROP TABLE categorias""")
# Aqui ele deleta a tabela e os registros dentro dela
# Alguns bancos fazem essa validação, deseja realmente deletar? Essa tabela não está vazia tem certeza que deseja deletar essa tabela?
# Você precisa deletar o conteúdo ou rocar um comando cascate que deleta todos os registros de todas as tabelas independente das dependencias.

cur.execute("""DROP TABLE categorias""")

In [ ]:
# Se executarmos o comando para consulta de tabelas, veja que não temos mais a tabela 'categorias'.
# Com esses comandos conseguimos criar estruturas, conseguimos alterar essas tabelas e também deletar
# As vezes precisamos criar uma view, ou precisamos criar uma table temporária, a gente precisa deletar essa tabela e ou alterar.
# Por exemplo uma ingestão que está utilizando 3 colunas, a gente precisa adicionar uma também no nosso ambiente ANALÍTICO 
# Precisa executar um SQL para alterar essa estruturação, é muito importante a gente dominar esses comandos SÂO MUITO IMPORTANTES quando estamos fazendo essa arquitetura 
# fazendo essa definição dos nossos dados independente se é no ambiente transacional ou analítico.

MÓDULO 03 - 1.3_C - SQL - DML E DQL

Agora utilizando essa estrutura que já utilizamos em outros vídeos, que é a utilização do pandas para criar um DataFrame.
Só que agora vamos trazer essa utilização para o SQlite.
Vamos para os passos

Com o Pandas e o SQLite importado, conseguimos trazer essas definições para dentro do nosso código.

In [ ]:
# Importar o pandas e o SQlte na primeira célula

import pandas as pd
import sqlite3
# Com o Pandas e o SQLite importado, conseguimos trazer essas definições para dentro do nosso código.

In [2]:
# Criando a conexão com o SQlite

con = sqlite3.connect('teste.db')

# Criando o cursos agora para poder exeexecutar os comandos no banco texte.db

cur = con.cursor()

In [3]:
# Agora vamos para os comandos SQl de DDL

cur.execute("""CREATE TABLE IF NOT EXISTS pessoas (
               id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
               nome TEXT NOT NULL,
               idade INTERGER NOT NULL,
               salario REAL NOT NULL    
    )""")

In [ ]:
# Comando para inserir valores nessa tabela

cur.execute("""
            INSERT INTO pessoas ('nome','idade','salario') VALUES 
            ('João', 12, 1000),
            ('Maria', 13, 2000),
            ('José', 14, 1500),
            ('Pedro', 15, 3000)
            """)
# Após as inserções precisamos confirmar 'commitar' essas alterações.
con.commit()

In [ ]:
# Comandos para consulta dos dados DQL - Select...

cur.execute("""SELECT * FROM pessoas""")

# Precisamos recuperar o resultado com Print
# Jogue dentro da variável 'resultado' pegando do cursor pegue todos os registros
resultado = cur.fetchall()
# Mostrando o resultado da consulta linha por linha com o FOR
# Para todas as linhas de 'resultado' vai printando 'resultado'
for linha in resultado:
    print(linha)

(1, 'João', 12, 1000.0)
(2, 'Maria', 13, 2000.0)
(3, 'José', 14, 1500.0)
(4, 'Pedro', 15, 3000.0)
(5, 'João', 12, 1000.0)
(6, 'Maria', 13, 2000.0)
(7, 'José', 14, 1500.0)
(8, 'Pedro', 15, 3000.0)

In [19]:
# Comandos para consulta dos dados DQL - 'Select' filtrando resultados

cur.execute("""SELECT * FROM pessoas where salario >= 1500""")
resultado = cur.fetchall()
for linha in resultado:
    print(linha)
    
cur.execute("""SELECT nome,idade FROM pessoas where salario >= 1500""")
resultado = cur.fetchall()
for linha in resultado:
    print(linha)

(10, 'Maria', 13, 2000.0)
(11, 'José', 14, 1500.0)
(12, 'Pedro', 15, 3000.0)
('Maria', 13)
('José', 14)
('Pedro', 15)

In [ ]:
# Fazendo a inserção de uma outra forma
# Mas antes precisamos limpar a tambela que fizemos o insert anteriormente
# Eu poderia filtrar com where """DELETE FROM pessoas WHERE id=1"""

cur.execute("""DELETE FROM pessoas""")
con.commit()

Aqui temos os registros do DataFrame que é um dicionário

Aqui vou er um FOR e vou ter a 'linha row' e 'no in' 'dataframe df' eu vou 'iteragir df.interrows() linha por linha 
Então eu estou lendo do dataframe não é da estrutura do dicionário mas é do DF, eu vou fazer um insert com o nome da pessoa, idade, e salario e vou definir algumas variáveis aqui. 
Essas variáveis vão ser populadas pela linha do dataframe que estou iterando e vou pegar por cada 'linha row' por nome, 'linha row' por idade, 'linha row' por salario e fazer uma
inserção em massa. 

1. Fazendo o DataFrame
2. Fazendo a inserção do DataFrame na minha tabela pessoas

In [17]:
import pandas as pd

dados = {
    'nome' : ['João','Maria','José','Pedro'],
    'idade': [12, 13, 14, 15],
    'salario': [1000, 2000, 1500, 3000] 
}
df = pd.DataFrame(dados)
print(df)

    nome  idade  salario
0   João     12     1000
1  Maria     13     2000
2   José     14     1500
3  Pedro     15     3000

In [ ]:
# Fazendo o comando de inserção em massa linha por linha na minha tabela
# Como temos 4 registros no dataframe 'df' ele vai fazer 4 vezes o comando de inserção

for _, row in df.iterrows():
    cur.execute("""INSERT INTO pessoas (nome, idade, salario) VALUES (?, ?, ?)""", (row['nome'], row['idade'], row['salario']))
    con.commit()
# Logo após você pode executar o comando de consulta DQL

Temos todas essas informações inseridas utilizando ambos. 
1. Criamos o DataFrame depois inserimos os dados
2. Podemos ler de um excel também, transformar esses dados em um DataFrame
3. E trazer esse dinamismo para efetuar um Insert em uma tabela de um banco de dados no qual já temos essa conexão.

MÓDULO 03 - 1.3_E - SQL - DATALAKE - CAMADA BRONZE

Nesse vídeo vamos utilizar tanto o SQlite quanto Pandas para simular um ambiente ponta a ponta de dados. Trabalhando com o SQL e com o Python vamos utilizar essas duas ferramentas para conseguir fazer um ponta a ponta de um pipeline de dados.

In [5]:
# Importanto as bibliotecas

import sqlite3
import pandas as pd

In [8]:
# 1. Criando o banco e a conexão com o banco
# 2. Criando o cursor para comandos com o banco

con = sqlite3.connect('datalike.db')
cur = con.cursor()

**Vamos utilizar os comandos osDDL (Data Definition Language): Create Alter Drop Truncate para fazermos a CRIAÇÃO desses registros.**

In [12]:
# criando as tabelas

# bronze_pessoas

cur.execute("""
            CREATE TABLE IF NOT EXISTS bronze_pessoas (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              nome TEXT,
              idade INTEGER,
              salario REAL                  
            )
            """)

# bronze_vendas

cur.execute(""" 
            CREATE TABLE IF NOT EXISTS bronze_vendas (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              vendedor TEXT,
              valor REAL,
              data TEXT
      )
      """)
# Comitar os comandos

con.commit()

**Vamos utilizar agora outros tipos de comandos os DML (Data Manipulation Language): Insert Update Delete para fazermos a INSERÇÃO desses registros.**

In [16]:
# Fazendo a Inserção nessas duas tabelas.
# Fazendo a Inserção para a tabela bronze_pessoas

# Comando cur.executemany() - Para fazer a inserção de vários registros.
# Essa função executemany() permite que passamos uma lista [] e depois passamos os valores das linhas que serão os dados do INSERT
# """INSERT INTO bronze_pessoas (nome, idade, salarios) VALUES (?,?,?) """, [ ('xxxx','xxxx','xxxx')]

cur.executemany("""
                INSERT INTO bronze_pessoas (nome, idade, salario) VALUES (?,?,?) """,
                [
                    ('João',25, 2000.00),
                    ('Maria',30, 2000.00),
                    ('José',35, 2000.00),
                    ('Ana',40, 2000.00),
                    ('Pedro',45, 2000.00),
                    ]
                )

In [18]:
# Fazendo a Inserção para a tabela bronze_vendas

cur.executemany("""
                INSERT INTO bronze_vendas (vendedor, valor, data) VALUES (?,?,?)""",
                [
                    ('João',4500.00,'2025-01-01'),
                    ('Maria',20000.00,'2025-01-02'),
                    ('José',7800.00,'2025-01-03'),
                    ('Ana',31000.00,'2025-01-04'),
                    ('Pedro',51000.00,'2025-01-05'),
                ]               
            )

Aqui já temos as informações de tabelas e dados dentro do nosso banco datalike.db dentro da nossa camada bronze.

In [19]:
# Fazendo consulta para ver as infromações.

cur.execute("""SELECT * FROM bronze_pessoas""")
resultado = cur.fetchall()
for linha in resultado:
    print(linha)
    
    cur.execute("""SELECT * FROM bronze_vendas""")
resultado = cur.fetchall()
for linha in resultado:
    print(linha)

(1, 'João', 25, 2000.0)
(2, 'Maria', 30, 2000.0)
(3, 'José', 35, 2000.0)
(4, 'Ana', 40, 2000.0)
(5, 'Pedro', 45, 2000.0)
(1, 'João', 4500.0, '2025-01-01')
(2, 'Maria', 20000.0, '2025-01-02')
(3, 'José', 7800.0, '2025-01-03')
(4, 'Ana', 31000.0, '2025-01-04')
(5, 'Pedro', 51000.0, '2025-01-05')

**MÓDULO 03 - 1.3_F - SQL - DATALAKE - CAMADA SILVER**

Dando continuidade agora na camada Silver, vamos adicionar o processamento da camada Bronze para a camada Silver

**SILVER**

O primeiro passo é ler da camada bronze, fazer a transformação e depois vamos salvar na camada Silver.

In [ ]:
# 1. Criar um DataFrame de pessoas onde eu vou utilizar o pandas pd. para ler utilizando uma query do SQL e vai selecionar todos os dados da camada Bronze da tabela
# bronze_pesoas utilizando a conexão que já abrimos
# O print(df_pessoas) é para olhar como está esses dados lá na camada Bronze

df_pessoas = pd.read_sql_query("SELECT * FROM bronze_pessoas", con)
print(df_pessoas)
# A mesma informação que fizemos lá na colsulta do cur.execute("""SELECT * FROM bronze_vendas""") temos ela aqui

   id   nome  idade  salario
0   1   João     25   2000.0
1   2  Maria     30   2000.0
2   3   José     35   2000.0
3   4    Ana     40   2000.0
4   5  Pedro     45   2000.0

In [21]:
# 2. Criar um DataFrame de vendas onde eu vou utilizar o pandas pd. para ler utilizando uma query do SQL e vai selecionar todos os dados da camada Bronze da tabela
df_vendas = pd.read_sql_query("SELECT * FROM bronze_vendas", con)
print(df_vendas)

   id vendedor    valor        data
0   1     João   4500.0  2025-01-01
1   2    Maria  20000.0  2025-01-02
2   3     José   7800.0  2025-01-03
3   4      Ana  31000.0  2025-01-04
4   5    Pedro  51000.0  2025-01-05

Aqui foi o seguinte, toda a informação que estavão lá na tabela, colocamos aqui no DataFrame do Pandas.
Aqui a gente conseguiu ler os dados da camada Bronze e trazer para um DataFrame

Agora vamos efetuar algumas transformações

In [27]:
# No DataFrame de df_pessoas vamos criar uma coluna chamada faixa_etaria ela vai ser igual = df_pessoas da coluna ['idade'].apply() aplicando a seguinte validação:
# Aqui temos a possibilidade de definir uma função, como não declarei a a função vou utilizar um recurso de funções lambda X, ou seja, elas são executadas nesse contexto.
# Não preciso declarar aqui a função - lambda x : ele vai efetuar a vakidação e verificar que 'Jovem' if x < 20 else ele vai retornar como 'Adulto'
# Posso colocar uma outra informação se X<=50 else senao ele vai ser 'Senior'

df_pessoas['faixa_etaria'] = df_pessoas['idade'].apply(
    lambda x : 'Jovem' if x < 30 else 'Adulto' if x <= 40 else 'Senior'
)

In [25]:
(df_pessoas)

   id   nome  idade  salario faixa_etaria
0   1   João     25   2000.0        Jovem
1   2  Maria     30   2000.0       Adulto
2   3   José     35   2000.0       Adulto
3   4    Ana     40   2000.0       Adulto
4   5  Pedro     45   2000.0       Adulto

In [ ]:
    # Fazendo uma alteração em df_vendas

    # df_vendas eu vou adicionar o dataframe de vendas df_vendas, e vou pegar a coluna do df_vendas onde o valor ['valor'] for > 5000
    # Aqui vamos acabar removendo que fez menos de 5000

    df_vendas[df_vendas['valor']>5000]
    # Posso Pintar tb
    print(df_vendas[df_vendas['valor']>5000])

   id vendedor    valor        data
1   2    Maria  20000.0  2025-01-02
2   3     José   7800.0  2025-01-03
3   4      Ana  31000.0  2025-01-04
4   5    Pedro  51000.0  2025-01-05

In [33]:
# Eu posso agora colocar esse resultado dentro da variável df_vendas, ou seja, o df_vendas vai ser uma atualização desse dataframe do prórpio dataframe já filtrado. 

df_vendas = df_vendas[df_vendas['valor']>5000]

In [34]:
# Visualizando o DataFrame 

print(df_vendas)

   id vendedor    valor        data
1   2    Maria  20000.0  2025-01-02
2   3     José   7800.0  2025-01-03
3   4      Ana  31000.0  2025-01-04
4   5    Pedro  51000.0  2025-01-05

**Criando as tabelas da Silver e depois a inserção**

In [ ]:
# Criando a tabela silver_pessoas

# aqui na tabela SILVER eu já nou vou utilizar esse AUTOINCREMENT por que eu vou utilizar o mesmo registro que já foi inserido na tabela bronze_pesoas
# Então tirar o AUTOINCREMENT daqui da silver_pessoas
cur.execute("""
            CREATE TABLE IF NOT EXISTS silver_pessoas(
            id INTEGER PRIMARY KEY,
            nome TEXT,
            idade INTEGER,
            salario REAL
            faixa_etaria TEXT
            )  
              """)
# Aqui em faixa_etaria TEXT foi o texto que agente criou, o enriquecimento que a gente fez nessa tabela a gente vai adicionar nessa coluna, ou seja,
# vai ter uma coluna nova na nossacamada Silver

In [37]:
# Criando a tabela silver_vendas

cur.execute("""
            CREATE TABLE IF NOT EXISTS silver_vendas (
            id INTERGER PRIMARY KEY,
            vendedor TEXT,
            valor REAL,
            data DATE
            )
            """)

In [40]:
con.commit()

In [ ]:
# Recuperando o DataFrame
df_pessoas

   id   nome  idade  salario faixa_etaria
0   1   João     25   2000.0        Jovem
1   2  Maria     30   2000.0       Adulto
2   3   José     35   2000.0       Adulto
3   4    Ana     40   2000.0       Adulto
4   5  Pedro     45   2000.0       Senior

In [ ]:
    # Criando agora os comandos de Insert

    # Agora vamos fazer o df_pessoas.to_sql() ou seja, enviar isso para um banco de dados utilizando os comandos de SQL ele vai converter esses Datframe para comandos SQL 
    # E vai salvar em uma tabela chamada silver_pessoas e aqui vamos colocar a conexão destino dessa comando, então a gente vai apontar para a conexão que já abrimos, aqui já estamos
    # passando essa variável da conexão
    # E aqui temos algumas opções: se existe if_exists='Replace' 'Se existe substitui' e vamos definir como o index falso index = false, dessa forma ele nao vai trazer essas 
    # informações de índice ele vai pegar somente as outras informações e salvar no nosso banco de dados.

    df_pessoas.to_sql('silver_pessoas', con, if_exists='replace', index = False)

5

In [53]:
# Criando agora os comandos de Insert
# Repetir o mesmo processo paa silver_vemdas

df_pessoas.to_sql('silver_vendas', con, if_exists='replace', index = False)

5

In [46]:
con.commit()

In [ ]:
# Visualizando os DataFrames
df_pessoas
df_pessoas

   id   nome  idade  salario faixa_etaria
0   1   João     25   2000.0        Jovem
1   2  Maria     30   2000.0       Adulto
2   3   José     35   2000.0       Adulto
3   4    Ana     40   2000.0       Adulto
4   5  Pedro     45   2000.0       Senior

In [55]:
# Vendo como os dados então no banco de dados

cur.execute("""SELECT * FROM silver_vendas""")
resultado = cur.fetchall()
for linha in resultado:
    print(linha)
    
    cur.execute("""SELECT * FROM silver_pessoas""")
resultado = cur.fetchall()
for linha in resultado:
    print(linha)

(1, 'João', 25, 2000.0, 'Jovem')
(2, 'Maria', 30, 2000.0, 'Adulto')
(3, 'José', 35, 2000.0, 'Adulto')
(4, 'Ana', 40, 2000.0, 'Adulto')
(5, 'Pedro', 45, 2000.0, 'Senior')
(1, 'João', 25, 2000.0, 'Jovem')
(2, 'Maria', 30, 2000.0, 'Adulto')
(3, 'José', 35, 2000.0, 'Adulto')
(4, 'Ana', 40, 2000.0, 'Adulto')
(5, 'Pedro', 45, 2000.0, 'Senior')

**MÓDULO 03 - 1.3_G - SQL - DATALAKE - CAMADA GOLD**

Agora iremos finalizar na camada GOLD


**Gold**

In [71]:
# Vamos criar as nossas tabelas já tendo o prefixo de Fatos e Dimensões
# Criando a tabela dim_pessoas
cur.execute("""
            CREATE TABLE IF NOT EXISTS dim_pessoas (
                id INTEGER PRIMARY KEY,
                nome TEXT,
                faixa_etaria TEXT               
            )            
            """)

In [72]:
# Criando a tabela fat_salarios
# Como é a tabela FATO alem da chave primaria temos que fazer o id da tabela dim_pessoa e pessoa_id 
# E fazer a chave estrangeira FOREIGN KEY para (pessoa_id) vai fazer referencia para a dim_pessoa na chave chamada id da tabela dim_pessoas

cur.execute("""
            CREATE TABLE IF NOT EXISTS fat_salarios (
                id INTEGER PRIMARY KEY,
                pessoa_id INTEGER,
                salario REAL,
                FOREIGN KEY (pessoa_id) REFERENCES dim_pessoas(id)                             
            )            
            """)

In [ ]:
# Criando a tabela fat_vendas

cur.execute("""
            CREATE TABLE IF NOT EXISTS fat_vendas (
                id INTEGER PRIMARY KEY,
                pessoa_id INTEGER, 
                total_vendas REAL,
                FOREIGN KEY (pessoa_id) REFERENCES dim_pessoas(id)             
                )
""")

In [74]:
# Comitando a criação dessas tabelas
con.commit()

In [76]:
# Agora precisamos trabalhar com esses dados para conseguirmos popular as nossas tabelas.
# dim_pessoas vai ser igual ao df_pessoas, mas eu quero do meu dataframe somente as colunas id, nome e faixa_etaria, ou seja, eu quero filtrar 
# somente essas colunas para criar a minha dimensão de pessoas.

dim_pessoas = df_pessoas[['id','nome','faixa_etaria']]
print(dim_pessoas)

   id   nome faixa_etaria
0   1   João        Jovem
1   2  Maria       Adulto
2   3   José       Adulto
3   4    Ana       Adulto
4   5  Pedro       Senior

In [ ]:
# Fazendo agora com a fat_salarios, a minha tabela de fatos de salários, ela vai ser igual ao df_pessoas, mas eu quero somente as colunas id e salario, ou seja, 
# eu quero filtrar somente essas colunas para criar a minha tabela de fatos de salários.
# Depois vou fazer o seguinte: Quero renomear a coluna de id para pessoa_id, para que eu consiga fazer a relação entre a minha tabela de fatos e a minha tabela de dimensão, ou seja,
# a minha tabela de fatos tem que ter a chave estrangeira que faz referencia a chave primária da minha tabela de dimensão. 

fat_salarios = df_pessoas[['id','salario']].rename(columns={'id':'pessoa_id'})

In [ ]:
# Vamos adicionar uma validação 
# Vamos criar a tablea fat_vendas que vai ser igual ao df_vendas.groupby para agrupar por vendedor e chamamos a função aggregate para agregar o valor total de vendas, ou seja,
# a soma do valor das vendas, ou seja, o total de vendas por vendedor. 
# agora fazemos o reset_index() para resetar o índice e transformar o vendedor em uma coluna normal, ou seja, ele não vai ser mais o índice do dataframe e sim uma coluna normal, 
# ou seja, ele vai ser um atributo da tabela de fatos.
# agora vamos renomear passando as colunas de vendedor : para nome e valor para : total_vendas
# agora vamos fazer a junção de merge dim_pessoas quando a gente tiver o nome, aqui ele vai fazer a junção pelo nome, ou sej,a um JOIN entre a tabela de fatos e a tabela de dimensão, 
# ou seja, ele vai pegar o nome do vendedor da tabela de fatos e vai comparar com o nome da tabela de dimensão, 
# quando ele encontrar ude 'id' com o 'total_vendas'
# e por fim vamos renomear a coluna 'id' para pessoa_id para que a gente consiga fazer a relação entre a tabela de fatos e a tabela de dimensão, ou seja,
# a chave estrangeira da tabela de fatos tem que ter o mesmo nome da chave primária da tabela de dimensão para que a gente consiga fazer essa relação.
fat_vendas = (df_vendas
              .groupby('vendedor')
              .agg({'valor': 'sum'})
              .reset_index()
              .rename(columns={'vendedor':'nome', 'valor':'total_vendas'})
              .merge(dim_pessoas, on='nome')[['id','total_vendas']]
              .rename(columns={'id':'pessoa_id'}))

Agora nos temos a nossa dimensão de pessoas dim_pessoas, temos a nossa fato salario fat_salario e a nossa fato e vendas fat_vendas.

Agora vamos salvar essas informações no destino

In [79]:
# Vamos salvar essas tabelas no banco de dados, ou seja, vamos fazer o processo de Insert utilizando o to_sql para cada uma dessas tabelas, 
# ou seja, a dim_pessoas, fat_salarios e fat_vendas
dim_pessoas.to_sql('dim_pessoas', con, if_exists='replace', index=False)
fat_salarios.to_sql('fat_salarios', con, if_exists='replace', index=False)
fat_vendas.to_sql('fat_vendas', con, if_exists='replace', index=False)

4

In [81]:
# Agora vamos recuperar essas informações para ver como estão lá no banco de dados, ou seja, vamos fazer uma consulta utilizando o cur.execute para cada uma dessas tabelas,
# ou seja, para a dim_pessoas, fat_salarios e fat_vendas
# O dataframe de dimensão de pessoas df_dim_pessoas vai ser um DataFrame pandas lendo o select utilizando a conexão e selecionando tudo da tabela dim_pessoas 
df_dim_pessoas = pd.read_sql_query("SELECT * FROM dim_pessoas", con)
print(df_dim_pessoas)

df_fat_salarios = pd.read_sql_query("SELECT * FROM fat_salarios", con)
print(df_fat_salarios)

df_fat_vendas = pd.read_sql_query("SELECT * FROM fat_vendas", con)
print(df_fat_vendas)

   id   nome faixa_etaria
0   1   João        Jovem
1   2  Maria       Adulto
2   3   José       Adulto
3   4    Ana       Adulto
4   5  Pedro       Senior
   pessoa_id  salario
0          1   2000.0
1          2   2000.0
2          3   2000.0
3          4   2000.0
4          5   2000.0
   pessoa_id  total_vendas
0          4       31000.0
1          3        7800.0
2          2       20000.0
3          5       51000.0

In [83]:
# Comitando as alterações
con.commit()
# Fechando a conexão
con.close()

Essa é a lógica que nos temos para estruturar em todas as camadas da arquitetura Medallion Bronze, Silve, Gold
No final quando finalizamos todas as alterações, a gente pode pegar a conexão e fazer o commit e também fechar a conexão con.close()

-> Aqui pegamos os dados brutos e fizemos a ingestão 
-> Não tivemos nenhum enriquecimento e tratamento de dados 
-> apenas salva na camada Bronze

-> Nos lemos esses dados da Bronze e passamos para a camada Silver
-> Na camada Silver fizemos um enriquecimento um ajuste e essas definições

-> Depois passamos para a camada Gold trazendo essa visão de FATOS e DIMENSÕES pensando no negócio aplicado

-> Aqui todos os ambientes foram estruturados, passamos por todas as camadads Medallion Bronze, Silve, Gold
-> Utilizamos SQL diversos comandos do SQl para fazer a criação de tabelas, inserção dos dados
-> Utilizamos o Python via Pandas para recuperar os dados para salvar os dados e para transofmrar os dados