**MÓDULO 04 - 1.4_H - PROJETO - DIMENSÃO NA GOLD E PULL REQUEST**

→ Vamos utilizar um outro Jupyter Notebook, ler os dados da camada Silver e levar para a Gold.

→ Salvar o notebook na pasta landing com o nome de refinamento

In [2]:
# Importando a biblioteca duckdb para criar o banco de dados em memória e a conexão com o banco de dados.
import duckdb

In [3]:
# Vamos fazer o import do duckdb para criar o banco de dados em memória e a conexão 
# com o banco de dados utilizando o comando duckdb.connect() para criar a conexão com o banco de dados.
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [4]:
# Vamos selecionar os produtos para verificarmos como estão os nossos dados na camada gold até aqui.
df = con.execute('SELECT * FROM produtos').fetchdf()
df.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10002    MARTELO         BT50            100     500.0
1  10001   PARAFUSO         BT10            100     100.0
2  10003      PREGO         BT10            100      50.0
3  10005    MACHADO         BT50            100     100.0
4  10004      SERRA         BT50            100     200.0
5  10001   PARAFUSO         BT10            100     100.0
6  10004      SERRA         BT50            100     200.0
7  10003      PREGO         BT10            100      50.0
8  10002    MARTELO         BT50            100     500.0
9  10005    MACHADO         BT50            100     100.0

In [5]:
# Agora eu vou criar uma Dimensão na camada Gold para os produtos, para isso eu vou criar uma tabela chamada dim_produtos e vou selecionar os campos id_produto, nome_produto, categoria_produto e preco_produto da tabela produtos e vou inserir esses dados na tabela dim_produtos.
# Mas antes vou delear as colunas id_categoria e id_fornecedor da tabela produtos, pois essas colunas não são necessárias para a criação da dimensão de produtos.
# O dataframe df2 vai ser igual ao df mas removendo as colunas id_categoria e id_fornecedor, para isso eu vou usar o método drop do pandas para remover essas colunas do dataframe df e criar um novo dataframe df2.
df2 = df.drop(columns=['id_categoria', 'id_fornecedor'])
df2.head(10)
# Pronto agora ele já tem uma estrutura sem dados duplicados e no modelo que queremos.

      id nm_produto  vl_preco
0  10002    MARTELO     500.0
1  10001   PARAFUSO     100.0
2  10003      PREGO      50.0
3  10005    MACHADO     100.0
4  10004      SERRA     200.0
5  10001   PARAFUSO     100.0
6  10004      SERRA     200.0
7  10003      PREGO      50.0
8  10002    MARTELO     500.0
9  10005    MACHADO     100.0

In [6]:
# Agora sim vamos criar a nossa tabela dim_produtos na camada gold, para isso eu vou usar o comando CREATE TABLE IF NOT EXISTS para criar a tabela dim_produtos e depois vou usar o comando INSERT INTO para inserir os dados do dataframe df2 na tabela dim_produtos.

con.execute('''
CREATE TABLE IF NOT EXISTS dim_produtos (
    id_produto BIGINT,
    nm_produto TEXT,
    VL_PRODUTO FLOAT
            )
''')

In [7]:
# Repare que a minha coluna VL_PRODUTO ficou com letra maiúscula, vou alterar para ficar com letra minúscula, para isso eu vou usar o comando ALTER TABLE para alterar o nome da coluna VL_PRODUTO para vl_produto.
con.execute('''ALTER TABLE dim_produtos RENAME COLUMN VL_PRODUTO TO vl_produto''')

In [8]:
# Agora vou consultar essa tabela para a nossa dim_produtos para verificar se os dados foram inseridos corretamente.
df_dim = con.execute('SELECT * FROM dim_produtos').fetchdf()
df_dim.head(10)

   id_produto nm_produto  vl_produto
0       10002    MARTELO       500.0
1       10001   PARAFUSO       100.0
2       10003      PREGO        50.0
3       10005    MACHADO       100.0
4       10004      SERRA       200.0
5       10001   PARAFUSO       100.0
6       10004      SERRA       200.0
7       10003      PREGO        50.0
8       10002    MARTELO       500.0
9       10005    MACHADO       100.0

In [28]:
# Vamos agora fazer a inserção dos dados do dataframe df2 na tabela dim_produtos, 
# para isso eu vou usar o comando INSERT INTO para inserir os dados do dataframe df2 na tabela dim_produtos.
con.execute('''INSERT INTO dim_produtos SELECT * FROM df2''')

In [ ]:
# Agora eu preciso fchar a conexão com o banco de dados para liberar os recursos utilizados pela conexão,
# para isso eu vou usar o comando con.close() para fechar a conexão com o banco de dados.
# Se não efetuar o procedimento de fechamento do banco, e caso precisamos efetuar uma outra conexão 
# com o banco de dados, pode ocorrer um erro de conexão,
# pois o banco de dados pode estar bloqueado por conta da conexão anterior que não foi fechada corretamente.
con.close()

Agora podemos fazer o seguinte, comitar esse aquivo para o nosso repositório.

1. Vamos abrir o terminal
2. Novo Terminal
2. Comando: git status
3. Aqui ele informou que a pasta script está pronta para ser adicionada
4. Comando: git add .
5. Comando: git status
6. Então todos os arquivos foram adicionados na nossa área de staged
7. Agora podemos fazer o commit deles
8. Aqui eu vou enviar o banco, para eu remover vou usar o comando: git restore --staged scripts/dados_duckdb.db
9. Vamos verificar: git status
10. Então como vemos aqui, somente os scripts estão na área de staged
11. Fazendo o commit: git commit -m 'script de transformacao de dados'
12. Após ter commitado enviar para o remoto, comando: git push
13. Pronto, enviei para a ára remota do Git, perceba que o banco 'dados_duckdb.db' ele ainda está aqui
14. Então eu enviei só os scripts no commit e para o remoto
15. Vamos dar uma olhada lá no GitHub para ver como ficou